export type BibleVerse = {
  id: number;
  text: string;
  reference: string;
};

export const BIBLE_VERSES: BibleVerse[] = [
  { id: 1, text: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God [is] with thee whithersoever thou goest.", reference: "Joshua 1:9" },
  { id: 2, text: "I can do all things through Christ which strengtheneth me.", reference: "Philippians 4:13" },
  { id: 3, text: "Commit thy works unto the LORD, and thy thoughts shall be established.", reference: "Proverbs 16:3" },
  { id: 4, text: "The LORD shall fight for you, and ye shall hold your peace.", reference: "Exodus 14:14" },
  { id: 5, text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding.", reference: "Proverbs 3:5" },
  { id: 6, text: "But they that wait upon the LORD shall renew [their] strength; they shall mount up with wings as eagles; they shall run, and not be weary; [and] they shall walk, and not faint.", reference: "Isaiah 40:31" },
  { id: 7, text: "Let all your things be done with charity.", reference: "1 Corinthians 16:14" },
  { id: 8, text: "And whatsoever ye do, do [it] heartily, as to the Lord, and not unto men;", reference: "Colossians 3:23" },
  { id: 9, text: "The thoughts of the diligent [tend] only to plenteousness; but of every one [that is] hasty only to want.", reference: "Proverbs 21:5" },
  { id: 10, text: "God [is] in the midst of her; she shall not be moved: God shall help her, [and that] right early.", reference: "Psalm 46:5" },
  { id: 11, text: "Casting all your care upon him; for he careth for you.", reference: "1 Peter 5:7" },
  { id: 12, text: "But Jesus beheld [them], and said unto them, With men this is impossible; but with God all things are possible.", reference: "Matthew 19:26" },
  { id: 13, text: "The LORD [is] my strength and my shield; my heart trusted in him, and I am helped: therefore my heart greatly rejoiceth; and with my song will I praise him.", reference: "Psalm 28:7" },
  { id: 14, text: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.", reference: "John 14:27" },
  { id: 15, text: "NUN. Thy word [is] a lamp unto my feet, and a light unto my path.", reference: "Psalm 119:105" },
  { id: 16, text: "And let us not be weary in well doing: for in due season we shall reap, if we faint not.", reference: "Galatians 6:9" },
  { id: 17, text: "Then he said unto them, Go your way, eat the fat, and drink the sweet, and send portions unto them for whom nothing is prepared: for [this] day [is] holy unto our Lord: neither be ye sorry; for the joy of the LORD is your strength.", reference: "Nehemiah 8:10" },
  { id: 18, text: "In all thy ways acknowledge him, and he shall direct thy paths.", reference: "Proverbs 3:6" },
  { id: 19, text: "Rejoicing in hope; patient in tribulation; continuing instant in prayer;", reference: "Romans 12:12" },
  { id: 20, text: "For the LORD giveth wisdom: out of his mouth [cometh] knowledge and understanding.", reference: "Proverbs 2:6" },
  { id: 21, text: "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me.", reference: "2 Corinthians 12:9" },
  { id: 22, text: "The LORD [is] nigh unto all them that call upon him, to all that call upon him in truth.", reference: "Psalm 145:18" },
  { id: 23, text: "Blessed [is] the man that endureth temptation: for when he is tried, he shall receive the crown of life, which the Lord hath promised to them that love him.", reference: "James 1:12" },
  { id: 24, text: "The fear of the LORD [is] the beginning of wisdom: and the knowledge of the holy [is] understanding.", reference: "Proverbs 9:10" },
  { id: 25, text: "He giveth power to the faint; and to [them that have] no might he increaseth strength.", reference: "Isaiah 40:29" },
  { id: 26, text: "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.", reference: "Matthew 5:16" },
  { id: 27, text: "[A Psalm] of David. The LORD [is] my light and my salvation; whom shall I fear? the LORD [is] the strength of my life; of whom shall I be afraid?", reference: "Psalm 27:1" },
  { id: 28, text: "Behold, God [is] my salvation; I will trust, and not be afraid: for the LORD JEHOVAH [is] my strength and [my] song; he also is become my salvation.", reference: "Isaiah 12:2" },
  { id: 29, text: "Wait on the LORD: be of good courage, and he shall strengthen thine heart: wait, I say, on the LORD.", reference: "Psalm 27:14" },
  { id: 30, text: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.", reference: "Romans 15:13" },
  { id: 31, text: "And God said, Let there be light: and there was light.", reference: "Genesis 1:3" },
  { id: 32, text: "And God saw the light, that [it was] good: and God divided the light from the darkness.", reference: "Genesis 1:4" },
  { id: 33, text: "And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day.", reference: "Genesis 1:5" },
  { id: 34, text: "And God said, Let there be lights in the firmament of the heaven to divide the day from the night; and let them be for signs, and for seasons, and for days, and years:", reference: "Genesis 1:14" },
  { id: 35, text: "And let them be for lights in the firmament of the heaven to give light upon the earth: and it was so.", reference: "Genesis 1:15" },
  { id: 36, text: "And God made two great lights; the greater light to rule the day, and the lesser light to rule the night: [he made] the stars also.", reference: "Genesis 1:16" },
  { id: 37, text: "And God set them in the firmament of the heaven to give light upon the earth,", reference: "Genesis 1:17" },
  { id: 38, text: "And to rule over the day and over the night, and to divide the light from the darkness: and God saw that [it was] good.", reference: "Genesis 1:18" },
  { id: 39, text: "And God blessed them, saying, Be fruitful, and multiply, and fill the waters in the seas, and let fowl multiply in the earth.", reference: "Genesis 1:22" },
  { id: 40, text: "And God blessed the seventh day, and sanctified it: because that in it he had rested from all his work which God created and made.", reference: "Genesis 2:3" },
  { id: 41, text: "And the LORD God said, [It is] not good that the man should be alone; I will make him an help meet for him.", reference: "Genesis 2:18" },
  { id: 42, text: "And Adam gave names to all cattle, and to the fowl of the air, and to every beast of the field; but for Adam there was not found an help meet for him.", reference: "Genesis 2:20" },
  { id: 43, text: "When thou tillest the ground, it shall not henceforth yield unto thee her strength; a fugitive and a vagabond shalt thou be in the earth.", reference: "Genesis 4:12" },
  { id: 44, text: "Male and female created he them; and blessed them, and called their name Adam, in the day when they were created.", reference: "Genesis 5:2" },
  { id: 45, text: "And he called his name Noah, saying, This [same] shall comfort us concerning our work and toil of our hands, because of the ground which the LORD hath cursed.", reference: "Genesis 5:29" },
  { id: 46, text: "But Noah found grace in the eyes of the LORD.", reference: "Genesis 6:8" },
  { id: 47, text: "And God blessed Noah and his sons, and said unto them, Be fruitful, and multiply, and replenish the earth.", reference: "Genesis 9:1" },
  { id: 48, text: "And he said, Blessed [be] the LORD God of Shem; and Canaan shall be his servant.", reference: "Genesis 9:26" },
  { id: 49, text: "And I will bless them that bless thee, and curse him that curseth thee: and in thee shall all families of the earth be blessed.", reference: "Genesis 12:3" },
  { id: 50, text: "And he blessed him, and said, Blessed [be] Abram of the most high God, possessor of heaven and earth:", reference: "Genesis 14:19" },
  { id: 51, text: "And blessed be the most high God, which hath delivered thine enemies into thy hand. And he gave him tithes of all.", reference: "Genesis 14:20" },
  { id: 52, text: "After these things the word of the LORD came unto Abram in a vision, saying, Fear not, Abram: I [am] thy shield, [and] thy exceeding great reward.", reference: "Genesis 15:1" },
  { id: 53, text: "And thou shalt go to thy fathers in peace; thou shalt be buried in a good old age.", reference: "Genesis 15:15" },
  { id: 54, text: "And as for Ishmael, I have heard thee: Behold, I have blessed him, and will make him fruitful, and will multiply him exceedingly; twelve princes shall he beget, and I will make him a great nation.", reference: "Genesis 17:20" },
  { id: 55, text: "And I will fetch a morsel of bread, and comfort ye your hearts; after that ye shall pass on: for therefore are ye come to your servant. And they said, So do, as thou hast said.", reference: "Genesis 18:5" },
  { id: 56, text: "Seeing that Abraham shall surely become a great and mighty nation, and all the nations of the earth shall be blessed in him?", reference: "Genesis 18:18" },
  { id: 57, text: "And God heard the voice of the lad; and the angel of God called to Hagar out of heaven, and said unto her, What aileth thee, Hagar? fear not; for God hath heard the voice of the lad where he [is].", reference: "Genesis 21:17" },
  { id: 58, text: "And in thy seed shall all the nations of the earth be blessed; because thou hast obeyed my voice.", reference: "Genesis 22:18" },
  { id: 59, text: "And Abraham was old, [and] well stricken in age: and the LORD had blessed Abraham in all things.", reference: "Genesis 24:1" },
  { id: 60, text: "And the man wondering at her held his peace, to wit whether the LORD had made his journey prosperous or not.", reference: "Genesis 24:21" },
  { id: 61, text: "And he said, Come in, thou blessed of the LORD; wherefore standest thou without? for I have prepared the house, and room for the camels.", reference: "Genesis 24:31" },
  { id: 62, text: "And the LORD hath blessed my master greatly; and he is become great: and he hath given him flocks, and herds, and silver, and gold, and menservants, and maidservants, and camels, and asses.", reference: "Genesis 24:35" },
  { id: 63, text: "And he said unto me, The LORD, before whom I walk, will send his angel with thee, and prosper thy way; and thou shalt take a wife for my son of my kindred, and of my father’s house:", reference: "Genesis 24:40" },
  { id: 64, text: "And I came this day unto the well, and said, O LORD God of my master Abraham, if now thou do prosper my way which I go:", reference: "Genesis 24:42" },
  { id: 65, text: "And I bowed down my head, and worshipped the LORD, and blessed the LORD God of my master Abraham, which had led me in the right way to take my master’s brother’s daughter unto his son.", reference: "Genesis 24:48" },
  { id: 66, text: "And he said unto them, Hinder me not, seeing the LORD hath prospered my way; send me away that I may go to my master.", reference: "Genesis 24:56" },
  { id: 67, text: "And they blessed Rebekah, and said unto her, Thou [art] our sister, be thou [the mother] of thousands of millions, and let thy seed possess the gate of those which hate them.", reference: "Genesis 24:60" },
  { id: 68, text: "And Rebekah lifted up her eyes, and when she saw Isaac, she lighted off the camel.", reference: "Genesis 24:64" },
  { id: 69, text: "And Isaac brought her into his mother Sarah’s tent, and took Rebekah, and she became his wife; and he loved her: and Isaac was comforted after his mother’s [death].", reference: "Genesis 24:67" },
  { id: 70, text: "And it came to pass after the death of Abraham, that God blessed his son Isaac; and Isaac dwelt by the well Lahairoi.", reference: "Genesis 25:11" },
  { id: 71, text: "And Isaac loved Esau, because he did eat of [his] venison: but Rebekah loved Jacob.", reference: "Genesis 25:28" },
  { id: 72, text: "And I will make thy seed to multiply as the stars of heaven, and will give unto thy seed all these countries; and in thy seed shall all the nations of the earth be blessed;", reference: "Genesis 26:4" },
  { id: 73, text: "And Abimelech said, What [is] this thou hast done unto us? one of the people might lightly have lien with thy wife, and thou shouldest have brought guiltiness upon us.", reference: "Genesis 26:10" },
  { id: 74, text: "Then Isaac sowed in that land, and received in the same year an hundredfold: and the LORD blessed him.", reference: "Genesis 26:12" },
  { id: 75, text: "And the LORD appeared unto him the same night, and said, I [am] the God of Abraham thy father: fear not, for I [am] with thee, and will bless thee, and multiply thy seed for my servant Abraham’s sake.", reference: "Genesis 26:24" },
  { id: 76, text: "That thou wilt do us no hurt, as we have not touched thee, and as we have done unto thee nothing but good, and have sent thee away in peace: thou [art] now the blessed of the LORD.", reference: "Genesis 26:29" },
  { id: 77, text: "And they rose up betimes in the morning, and sware one to another: and Isaac sent them away, and they departed from him in peace.", reference: "Genesis 26:31" },
  { id: 78, text: "And make me savoury meat, such as I love, and bring [it] to me, that I may eat; that my soul may bless thee before I die.", reference: "Genesis 27:4" },
  { id: 79, text: "Go now to the flock, and fetch me from thence two good kids of the goats; and I will make them savoury meat for thy father, such as he loveth:", reference: "Genesis 27:9" },
  { id: 80, text: "And he went, and fetched, and brought [them] to his mother: and his mother made savoury meat, such as his father loved.", reference: "Genesis 27:14" },
  { id: 81, text: "And he discerned him not, because his hands were hairy, as his brother Esau’s hands: so he blessed him.", reference: "Genesis 27:23" },
  { id: 82, text: "And he came near, and kissed him: and he smelled the smell of his raiment, and blessed him, and said, See, the smell of my son [is] as the smell of a field which the LORD hath blessed:", reference: "Genesis 27:27" },
  { id: 83, text: "And Esau hated Jacob because of the blessing wherewith his father blessed him: and Esau said in his heart, The days of mourning for my father are at hand; then will I slay my brother Jacob.", reference: "Genesis 27:41" },
  { id: 84, text: "And Isaac called Jacob, and blessed him, and charged him, and said unto him, Thou shalt not take a wife of the daughters of Canaan.", reference: "Genesis 28:1" },
  { id: 85, text: "And he lighted upon a certain place, and tarried there all night, because the sun was set; and he took of the stones of that place, and put [them for] his pillows, and lay down in that place to sleep.", reference: "Genesis 28:11" },
  { id: 86, text: "So that I come again to my father’s house in peace; then shall the LORD be my God:", reference: "Genesis 28:21" },
  { id: 87, text: "And Jacob loved Rachel; and said, I will serve thee seven years for Rachel thy younger daughter.", reference: "Genesis 29:18" },
  { id: 88, text: "And Jacob served seven years for Rachel; and they seemed unto him [but] a few days, for the love he had to her.", reference: "Genesis 29:20" },
  { id: 89, text: "And he went in also unto Rachel, and he loved also Rachel more than Leah, and served with him yet seven other years.", reference: "Genesis 29:30" },
  { id: 90, text: "And Leah conceived, and bare a son, and she called his name Reuben: for she said, Surely the LORD hath looked upon my affliction; now therefore my husband will love me.", reference: "Genesis 29:32" },
  { id: 91, text: "And Leah said, Happy am I, for the daughters will call me blessed: and she called his name Asher.", reference: "Genesis 30:13" },
  { id: 92, text: "And Laban said unto him, I pray thee, if I have found favour in thine eyes, [tarry: for] I have learned by experience that the LORD hath blessed me for thy sake.", reference: "Genesis 30:27" },
  { id: 93, text: "For [it was] little which thou hadst before I [came], and it is [now] increased unto a multitude; and the LORD hath blessed thee since my coming: and now when shall I provide for mine own house also?", reference: "Genesis 30:30" },
  { id: 94, text: "And it came to pass, whensoever the stronger cattle did conceive, that Jacob laid the rods before the eyes of the cattle in the gutters, that they might conceive among the rods.", reference: "Genesis 30:41" },
  { id: 95, text: "But when the cattle were feeble, he put [them] not in: so the feebler were Laban’s, and the stronger Jacob’s.", reference: "Genesis 30:42" },
  { id: 96, text: "And early in the morning Laban rose up, and kissed his sons and his daughters, and blessed them: and Laban departed, and returned unto his place.", reference: "Genesis 31:55" },
  { id: 97, text: "And I have oxen, and asses, flocks, and menservants, and womenservants: and I have sent to tell my lord, that I may find grace in thy sight.", reference: "Genesis 32:5" },
  { id: 98, text: "And Jacob asked [him], and said, Tell [me], I pray thee, thy name. And he said, Wherefore [is] it [that] thou dost ask after my name? And he blessed him there.", reference: "Genesis 32:29" },
  { id: 99, text: "And he said, What [meanest] thou by all this drove which I met? And he said, [These are] to find grace in the sight of my lord.", reference: "Genesis 33:8" },
  { id: 100, text: "Let my lord, I pray thee, pass over before his servant: and I will lead on softly, according as the cattle that goeth before me and the children be able to endure, until I come unto my lord unto Seir.", reference: "Genesis 33:14" },
  { id: 101, text: "And Esau said, Let me now leave with thee [some] of the folk that [are] with me. And he said, What needeth it? let me find grace in the sight of my lord.", reference: "Genesis 33:15" },
  { id: 102, text: "And his soul clave unto Dinah the daughter of Jacob, and he loved the damsel, and spake kindly unto the damsel.", reference: "Genesis 34:3" },
  { id: 103, text: "And Jacob heard that he had defiled Dinah his daughter: now his sons were with his cattle in the field: and Jacob held his peace until they were come.", reference: "Genesis 34:5" },
  { id: 104, text: "And Shechem said unto her father and unto her brethren, Let me find grace in your eyes, and what ye shall say unto me I will give.", reference: "Genesis 34:11" },
  { id: 105, text: "And the young man deferred not to do the thing, because he had delight in Jacob’s daughter: and he [was] more honourable than all the house of his father.", reference: "Genesis 34:19" },
  { id: 106, text: "And God appeared unto Jacob again, when he came out of Padanaram, and blessed him.", reference: "Genesis 35:9" },
  { id: 107, text: "And it came to pass, when she was in hard labour, that the midwife said unto her, Fear not; thou shalt have this son also.", reference: "Genesis 35:17" },
  { id: 108, text: "Now Israel loved Joseph more than all his children, because he [was] the son of his old age: and he made him a coat of [many] colours.", reference: "Genesis 37:3" },
  { id: 109, text: "And when his brethren saw that their father loved him more than all his brethren, they hated him, and could not speak peaceably unto him.", reference: "Genesis 37:4" },
  { id: 110, text: "And all his sons and all his daughters rose up to comfort him; but he refused to be comforted; and he said, For I will go down into the grave unto my son mourning. Thus his father wept for him.", reference: "Genesis 37:35" },
  { id: 111, text: "And in process of time the daughter of Shuah Judah’s wife died; and Judah was comforted, and went up unto his sheepshearers to Timnath, he and his friend Hirah the Adullamite.", reference: "Genesis 38:12" },
  { id: 112, text: "And the LORD was with Joseph, and he was a prosperous man; and he was in the house of his master the Egyptian.", reference: "Genesis 39:2" },
  { id: 113, text: "And his master saw that the LORD [was] with him, and that the LORD made all that he did to prosper in his hand.", reference: "Genesis 39:3" },
  { id: 114, text: "And Joseph found grace in his sight, and he served him: and he made him overseer over his house, and all [that] he had he put into his hand.", reference: "Genesis 39:4" },
  { id: 115, text: "The keeper of the prison looked not to any thing [that was] under his hand; because the LORD was with him, and [that] which he did, the LORD made [it] to prosper.", reference: "Genesis 39:23" },
  { id: 116, text: "And Joseph answered Pharaoh, saying, [It is] not in me: God shall give Pharaoh an answer of peace.", reference: "Genesis 41:16" },
  { id: 117, text: "And he said, Peace [be] to you, fear not: your God, and the God of your father, hath given you treasure in your sacks: I had your money. And he brought Simeon out unto them.", reference: "Genesis 43:23" },
  { id: 118, text: "As soon as the morning was light, the men were sent away, they and their asses.", reference: "Genesis 44:3" },
  { id: 119, text: "And he said, God forbid that I should do so: [but] the man in whose hand the cup is found, he shall be my servant; and as for you, get you up in peace unto your father.", reference: "Genesis 44:17" },
  { id: 120, text: "And we said unto my lord, We have a father, an old man, and a child of his old age, a little one; and his brother is dead, and he alone is left of his mother, and his father loveth him.", reference: "Genesis 44:20" },
  { id: 121, text: "And he said, I [am] God, the God of thy father: fear not to go down into Egypt; for I will there make of thee a great nation:", reference: "Genesis 46:3" },
  { id: 122, text: "And Joseph brought in Jacob his father, and set him before Pharaoh: and Jacob blessed Pharaoh.", reference: "Genesis 47:7" },
  { id: 123, text: "And Jacob blessed Pharaoh, and went out from before Pharaoh.", reference: "Genesis 47:10" },
  { id: 124, text: "And they said, Thou hast saved our lives: let us find grace in the sight of my lord, and we will be Pharaoh’s servants.", reference: "Genesis 47:25" },
  { id: 125, text: "And [one] told Jacob, and said, Behold, thy son Joseph cometh unto thee: and Israel strengthened himself, and sat upon the bed.", reference: "Genesis 48:2" },
  { id: 126, text: "And Jacob said unto Joseph, God Almighty appeared unto me at Luz in the land of Canaan, and blessed me,", reference: "Genesis 48:3" },
  { id: 127, text: "And he blessed Joseph, and said, God, before whom my fathers Abraham and Isaac did walk, the God which fed me all my life long unto this day,", reference: "Genesis 48:15" },
  { id: 128, text: "And he blessed them that day, saying, In thee shall Israel bless, saying, God make thee as Ephraim and as Manasseh: and he set Ephraim before Manasseh.", reference: "Genesis 48:20" },
  { id: 129, text: "Reuben, thou [art] my firstborn, my might, and the beginning of my strength, the excellency of dignity, and the excellency of power:", reference: "Genesis 49:3" },
  { id: 130, text: "Judah [is] a lion’s whelp: from the prey, my son, thou art gone up: he stooped down, he couched as a lion, and as an old lion; who shall rouse him up?", reference: "Genesis 49:9" },
  { id: 131, text: "Issachar [is] a strong ass couching down between two burdens:", reference: "Genesis 49:14" },
  { id: 132, text: "I have waited for thy salvation, O LORD.", reference: "Genesis 49:18" },
  { id: 133, text: "But his bow abode in strength, and the arms of his hands were made strong by the hands of the mighty [God] of Jacob; (from thence [is] the shepherd, the stone of Israel:)", reference: "Genesis 49:24" },
  { id: 134, text: "All these [are] the twelve tribes of Israel: and this [is it] that their father spake unto them, and blessed them; every one according to his blessing he blessed them.", reference: "Genesis 49:28" },
  { id: 135, text: "And when the days of his mourning were past, Joseph spake unto the house of Pharaoh, saying, If now I have found grace in your eyes, speak, I pray you, in the ears of Pharaoh, saying,", reference: "Genesis 50:4" },
  { id: 136, text: "And Joseph said unto them, Fear not: for [am] I in the place of God?", reference: "Genesis 50:19" },
  { id: 137, text: "Now therefore fear ye not: I will nourish you, and your little ones. And he comforted them, and spake kindly unto them.", reference: "Genesis 50:21" },
  { id: 138, text: "And the shepherds came and drove them away: but Moses stood up and helped them, and watered their flock.", reference: "Exodus 2:17" },
  { id: 139, text: "Then the LORD said unto Moses, Now shalt thou see what I will do to Pharaoh: for with a strong hand shall he let them go, and with a strong hand shall he drive them out of his land.", reference: "Exodus 6:1" },
  { id: 140, text: "And the LORD turned a mighty strong west wind, which took away the locusts, and cast them into the Red sea; there remained not one locust in all the coasts of Egypt.", reference: "Exodus 10:19" },
  { id: 141, text: "They saw not one another, neither rose any from his place for three days: but all the children of Israel had light in their dwellings.", reference: "Exodus 10:23" },
  { id: 142, text: "And it shall be for a sign unto thee upon thine hand, and for a memorial between thine eyes, that the LORD’S law may be in thy mouth: for with a strong hand hath the LORD brought thee out of Egypt.", reference: "Exodus 13:9" },
  { id: 143, text: "And it shall be when thy son asketh thee in time to come, saying, What [is] this? that thou shalt say unto him, By strength of hand the LORD brought us out from Egypt, from the house of bondage:", reference: "Exodus 13:14" },
  { id: 144, text: "And it shall be for a token upon thine hand, and for frontlets between thine eyes: for by strength of hand the LORD brought us forth out of Egypt.", reference: "Exodus 13:16" },
  { id: 145, text: "And the LORD went before them by day in a pillar of a cloud, to lead them the way; and by night in a pillar of fire, to give them light; to go by day and night:", reference: "Exodus 13:21" },
  { id: 146, text: "And Moses stretched out his hand over the sea; and the LORD caused the sea to go [back] by a strong east wind all that night, and made the sea dry [land], and the waters were divided.", reference: "Exodus 14:21" },
  { id: 147, text: "The LORD [is] my strength and song, and he is become my salvation: he [is] my God, and I will prepare him an habitation; my father’s God, and I will exalt him.", reference: "Exodus 15:2" },
  { id: 148, text: "Thou in thy mercy hast led forth the people [which] thou hast redeemed: thou hast guided [them] in thy strength unto thy holy habitation.", reference: "Exodus 15:13" },
  { id: 149, text: "And the name of the other [was] Eliezer; for the God of my father, [said he, was] mine help, and delivered me from the sword of Pharaoh:", reference: "Exodus 18:4" },
  { id: 150, text: "And Jethro said, Blessed [be] the LORD, who hath delivered you out of the hand of the Egyptians, and out of the hand of Pharaoh, who hath delivered the people from under the hand of the Egyptians.", reference: "Exodus 18:10" },
  { id: 151, text: "If thou shalt do this thing, and God command thee [so], then thou shalt be able to endure, and all this people shall also go to their place in peace.", reference: "Exodus 18:23" },
  { id: 152, text: "And shewing mercy unto thousands of them that love me, and keep my commandments.", reference: "Exodus 20:6" },
  { id: 153, text: "For [in] six days the LORD made heaven and earth, the sea, and all that in them [is], and rested the seventh day: wherefore the LORD blessed the sabbath day, and hallowed it.", reference: "Exodus 20:11" },
  { id: 154, text: "And all the people saw the thunderings, and the lightnings, and the noise of the trumpet, and the mountain smoking: and when the people saw [it], they removed, and stood afar off.", reference: "Exodus 20:18" },
  { id: 155, text: "And Moses said unto the people, Fear not: for God is come to prove you, and that his fear may be before your faces, that ye sin not.", reference: "Exodus 20:20" },
  { id: 156, text: "And if the servant shall plainly say, I love my master, my wife, and my children; I will not go out free:", reference: "Exodus 21:5" },
  { id: 157, text: "If thou see the ass of him that hateth thee lying under his burden, and wouldest forbear to help him, thou shalt surely help with him.", reference: "Exodus 23:5" },
  { id: 158, text: "And he sent young men of the children of Israel, which offered burnt offerings, and sacrificed peace offerings of oxen unto the LORD.", reference: "Exodus 24:5" },
  { id: 159, text: "Oil for the light, spices for anointing oil, and for sweet incense,", reference: "Exodus 25:6" },
  { id: 160, text: "And thou shalt make the seven lamps thereof: and they shall light the lamps thereof, that they may give light over against it.", reference: "Exodus 25:37" },
  { id: 161, text: "And thou shalt command the children of Israel, that they bring thee pure oil olive beaten for the light, to cause the lamp to burn always.", reference: "Exodus 27:20" },
  { id: 162, text: "And when Aaron lighteth the lamps at even, he shall burn incense upon it, a perpetual incense before the LORD throughout your generations.", reference: "Exodus 30:8" },
  { id: 163, text: "And I have filled him with the spirit of God, in wisdom, and in understanding, and in knowledge, and in all manner of workmanship,", reference: "Exodus 31:3" },
  { id: 164, text: "And they rose up early on the morrow, and offered burnt offerings, and brought peace offerings; and the people sat down to eat and to drink, and rose up to play.", reference: "Exodus 32:6" },
  { id: 165, text: "Now therefore, I pray thee, if I have found grace in thy sight, shew me now thy way, that I may know thee, that I may find grace in thy sight: and consider that this nation [is] thy people.", reference: "Exodus 33:13" },
  { id: 166, text: "And the LORD said unto Moses, I will do this thing also that thou hast spoken: for thou hast found grace in my sight, and I know thee by name.", reference: "Exodus 33:17" },
  { id: 167, text: "And oil for the light, and spices for anointing oil, and for the sweet incense,", reference: "Exodus 35:8" },
  { id: 168, text: "The candlestick also for the light, and his furniture, and his lamps, with the oil for the light,", reference: "Exodus 35:14" },
  { id: 169, text: "And all the women whose heart stirred them up in wisdom spun goats’ [hair].", reference: "Exodus 35:26" },
  { id: 170, text: "And spice, and oil for the light, and for the anointing oil, and for the sweet incense.", reference: "Exodus 35:28" },
  { id: 171, text: "And he hath filled him with the spirit of God, in wisdom, in understanding, and in knowledge, and in all manner of workmanship;", reference: "Exodus 35:31" },
  { id: 172, text: "And Moses called Bezaleel and Aholiab, and every wise hearted man, in whose heart the LORD had put wisdom, [even] every one whose heart stirred him up to come unto the work to do it:", reference: "Exodus 36:2" },
  { id: 173, text: "The pure candlestick, [with] the lamps thereof, [even with] the lamps to be set in order, and all the vessels thereof, and the oil for light,", reference: "Exodus 39:37" },
  { id: 174, text: "And Moses did look upon all the work, and, behold, they had done it as the LORD had commanded, even so had they done it: and Moses blessed them.", reference: "Exodus 39:43" },
  { id: 175, text: "And thou shalt bring in the table, and set in order the things that are to be set in order upon it; and thou shalt bring in the candlestick, and light the lamps thereof.", reference: "Exodus 40:4" },
  { id: 176, text: "And he lighted the lamps before the LORD; as the LORD commanded Moses.", reference: "Exodus 40:25" },
  { id: 177, text: "And if his oblation [be] a sacrifice of peace offering, if he offer [it] of the herd; whether [it be] a male or female, he shall offer it without blemish before the LORD.", reference: "Leviticus 3:1" },
  { id: 178, text: "And he shall offer of the sacrifice of the peace offering an offering made by fire unto the LORD; the fat that covereth the inwards, and all the fat that [is] upon the inwards,", reference: "Leviticus 3:3" },
  { id: 179, text: "And if his offering for a sacrifice of peace offering unto the LORD [be] of the flock; male or female, he shall offer it without blemish.", reference: "Leviticus 3:6" },
  { id: 180, text: "As it was taken off from the bullock of the sacrifice of peace offerings: and the priest shall burn them upon the altar of the burnt offering.", reference: "Leviticus 4:10" },
  { id: 181, text: "And he shall burn all his fat upon the altar, as the fat of the sacrifice of peace offerings: and the priest shall make an atonement for him as concerning his sin, and it shall be forgiven him.", reference: "Leviticus 4:26" },
  { id: 182, text: "And this [is] the law of the sacrifice of peace offerings, which he shall offer unto the LORD.", reference: "Leviticus 7:11" },
  { id: 183, text: "Besides the cakes, he shall offer [for] his offering leavened bread with the sacrifice of thanksgiving of his peace offerings.", reference: "Leviticus 7:13" },
  { id: 184, text: "And of it he shall offer one out of the whole oblation [for] an heave offering unto the LORD, [and] it shall be the priest’s that sprinkleth the blood of the peace offerings.", reference: "Leviticus 7:14" },
  { id: 185, text: "And the flesh of the sacrifice of his peace offerings for thanksgiving shall be eaten the same day that it is offered; he shall not leave any of it until the morning.", reference: "Leviticus 7:15" },
  { id: 186, text: "But the soul that eateth [of] the flesh of the sacrifice of peace offerings, that [pertain] unto the LORD, having his uncleanness upon him, even that soul shall be cut off from his people.", reference: "Leviticus 7:20" },
  { id: 187, text: "Speak unto the children of Israel, saying, He that offereth the sacrifice of his peace offerings unto the LORD shall bring his oblation unto the LORD of the sacrifice of his peace offerings.", reference: "Leviticus 7:29" },
  { id: 188, text: "And the right shoulder shall ye give unto the priest [for] an heave offering of the sacrifices of your peace offerings.", reference: "Leviticus 7:32" },
  { id: 189, text: "He among the sons of Aaron, that offereth the blood of the peace offerings, and the fat, shall have the right shoulder for [his] part.", reference: "Leviticus 7:33" },
  { id: 190, text: "This [is] the law of the burnt offering, of the meat offering, and of the sin offering, and of the trespass offering, and of the consecrations, and of the sacrifice of the peace offerings;", reference: "Leviticus 7:37" },
  { id: 191, text: "Also a bullock and a ram for peace offerings, to sacrifice before the LORD; and a meat offering mingled with oil: for to day the LORD will appear unto you.", reference: "Leviticus 9:4" },
  { id: 192, text: "He slew also the bullock and the ram [for] a sacrifice of peace offerings, which [was] for the people: and Aaron’s sons presented unto him the blood, which he sprinkled upon the altar round about,", reference: "Leviticus 9:18" },
  { id: 193, text: "And Aaron lifted up his hand toward the people, and blessed them, and came down from offering of the sin offering, and the burnt offering, and peace offerings.", reference: "Leviticus 9:22" },
  { id: 194, text: "And Moses and Aaron went into the tabernacle of the congregation, and came out, and blessed the people: and the glory of the LORD appeared unto all the people.", reference: "Leviticus 9:23" },
  { id: 195, text: "Then Moses said unto Aaron, This [is it] that the LORD spake, saying, I will be sanctified in them that come nigh me, and before all the people I will be glorified. And Aaron held his peace.", reference: "Leviticus 10:3" },
  { id: 196, text: "Do not drink wine nor strong drink, thou, nor thy sons with thee, when ye go into the tabernacle of the congregation, lest ye die: [it shall be] a statute for ever throughout your generations:", reference: "Leviticus 10:9" },
  { id: 197, text: "And Moses diligently sought the goat of the sin offering, and, behold, it was burnt: and he was angry with Eleazar and Ithamar, the sons of Aaron [which were] left [alive], saying,", reference: "Leviticus 10:16" },
  { id: 198, text: "Whatsoever parteth the hoof, and is clovenfooted, [and] cheweth the cud, among the beasts, that shall ye eat.", reference: "Leviticus 11:3" },
  { id: 199, text: "And the swine, though he divide the hoof, and be clovenfooted, yet he cheweth not the cud; he [is] unclean to you.", reference: "Leviticus 11:7" },
  { id: 200, text: "[The carcases] of every beast which divideth the hoof, and [is] not clovenfooted, nor cheweth the cud, [are] unclean unto you: every one that toucheth them shall be unclean.", reference: "Leviticus 11:26" },
];
